services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      retries: 5
  backend:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SERVER_ADDRESS=0.0.0.0:8081
      - DRIVER_SOURCE=postgres://root:secret@postgres:5432/simple_bank?sslmode=disable
