// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, arg DeleteAccountParams) error
	DeleteEntry(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, arg GetAccountParams) (Account, error)
	GetAccountForUpdate(ctx context.Context, arg GetAccountForUpdateParams) (Account, error)
	GetEntries(ctx context.Context, arg GetEntriesParams) ([]Entry, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetTransferById(ctx context.Context, id int64) (Transfer, error)
	GetTransfersByFromAccountId(ctx context.Context, arg GetTransfersByFromAccountIdParams) ([]Transfer, error)
	GetTransfersByFromAndToAccountId(ctx context.Context, arg GetTransfersByFromAndToAccountIdParams) ([]Transfer, error)
	GetTransfersByToAccountId(ctx context.Context, arg GetTransfersByToAccountIdParams) ([]Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
